# Generated by Django 4.2.30 on 2026-05-11 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_generique', models.CharField(max_length=150)),
                ('nom_commercial', models.CharField(blank=True, max_length=150)),
                ('forme', models.CharField(choices=[('comprime', 'Comprimé'), ('sirop', 'Sirop'), ('gelule', 'Gélule'), ('injectable', 'Injectable'), ('pommade', 'Pommade'), ('suppositoire', 'Suppositoire'), ('collyre', 'Collyre')], max_length=20)),
                ('dosage', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('fabricant', models.CharField(blank=True, max_length=150)),
                ('prescription', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicaments', to='medicaments.categorie')),
            ],
            options={
                'db_table': 'medicament',
                'unique_together': {('nom_generique', 'dosage', 'forme')},
            },
        ),
    ]
