# Generated by Django 4.2.30 on 2026-05-11 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_dernier_message', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('fermee', 'Fermée')], default='ouverte', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='accounts.client')),
            ],
            options={
                'db_table': 'discussion',
            },
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pharmacie_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('ninea', models.CharField(max_length=50, unique=True)),
                ('licence', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('suspendu', 'Suspendu')], default='en_attente', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('nombre_avis', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'pharmacie',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pharmacies.discussion')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
                'ordering': ['date_envoi'],
            },
        ),
        migrations.AddField(
            model_name='discussion',
            name='pharmacie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='pharmacies.pharmacie'),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('note', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reponse', models.TextField(blank=True, null=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='accounts.client')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='pharmacies.pharmacie')),
            ],
            options={
                'db_table': 'commentaire',
            },
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('ouverture', models.TimeField(blank=True, null=True)),
                ('fermeture', models.TimeField(blank=True, null=True)),
                ('ferme', models.BooleanField(default=False)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='pharmacies.pharmacie')),
            ],
            options={
                'db_table': 'horaire',
                'unique_together': {('pharmacie', 'jour')},
            },
        ),
    ]
