# Generated by Django 4.2.30 on 2026-05-11 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament_recherche', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nombre_resultats', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recherches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historique_recherche',
                'ordering': ['-date'],
            },
        ),
    ]
