# Generated by Django 4.2.30 on 2026-05-11 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicaments', '0001_initial'),
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('seuil_alerte', models.IntegerField(default=10)),
                ('disponible', models.BooleanField(default=False)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='medicaments.medicament')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='pharmacies.pharmacie')),
            ],
            options={
                'db_table': 'stock',
                'unique_together': {('pharmacie', 'medicament')},
            },
        ),
    ]
