# Generated by Django 4.2.30 on 2026-05-11 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicaments', '0001_initial'),
        ('accounts', '0001_initial'),
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('disponibilite', 'Médicament disponible'), ('stock_faible', 'Stock faible'), ('validation', 'Validation pharmacie'), ('message', 'Nouveau message')], default='disponibilite', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('rayon', models.IntegerField(default=5000)),
                ('date_notification', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='accounts.client')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='medicaments.medicament')),
                ('pharmacie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='pharmacies.pharmacie')),
            ],
            options={
                'db_table': 'alerte',
            },
        ),
    ]
